### ISSUE TITLE
Bug: Why does pricing in gcosts not reflect Google's pricing calculator?

### ISSUE THREAD

**Issue by max-l-weaver** [Cyclenerd/google-cloud-pricing-cost-calculator#239]
**Describe the bug**
I'm loving `gcosts` btw, but I was interested as to why the pricing within the `pricing.yml` does not reflect pricing using Google's [pricing calculator](https://cloud.google.com/products/calculator)?

I've checked Google's pricing calculator against the SKU prices and they seem both accurate so I was just curious more than anything.

I realise that the calculator is an estimate too

**To Reproduce**
1. Monthly cost of n1-standard-2 in `europe-west2` via calculator is [$89.35](https://cloud.google.com/products/calculator?hl=en&dl=CiRlMjgxZjJhOS00MjljLTRhOGItOGNmNy1mZmZlNTdkMTUwYWQQCBokRTRDQUQ0OEMtMzY4OC00RUZCLThDMzUtODc1QTk5OEU2NjJE)
2. Compare with pricing in latest `pricing.yml` which is $62.xx:
```yaml
        europe-west2:
          hour: 0.122395
          hour_spot: 0.025465
          month: 62.543845
          month_1y: 56.235185
          month_3y: 40.1697465
          month_spot: 18.58945
```

**Expected behavior**
I would expect the two comparisons to match, but I _could_ be missing a vital part of the puzzle here

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser n/a
 - Version v3.0.2
