### ISSUE TITLE
Feature request: Add Data Retrieval Information 

### ISSUE THREAD

**Issue by jjjermiah** [Cyclenerd/google-cloud-pricing-cost-calculator#85]
**Is your feature request related to a problem? Please describe.**
Looking to create a data portal for a large amount of data, and need to take into consideration Data Retrieval for the non-standard buckets. 

**Describe the solution you'd like**
The option of adding in "data retrieval" in the Bucket section indicating the estimated data to be downloaded. 
i.e:
```
buckets:
  - name: rawdata_nearline
    region: northamerica-northeast2
    class: nearline
    data: 50000
    data retrieval: 10000
```

**Describe alternatives you've considered**
I have currently just hacked the pricing.yml file to add the following as a `bucket: class` 
```
    retrieval_archiv:
      cost:
        northamerica-northeast2:
          month: 0.05
    retrieval_coldline:
      cost:
        northamerica-northeast2:
          month: 0.02
    retrieval_nearline:
      cost:
        northamerica-northeast2:
          month: 0.01
```
however this requires me to create an entire new section in my resources.yml
```
buckets:
  - name: rawdata_nearline
    region: northamerica-northeast2
    class: nearline
    data: 50000
  - name: sgc-rawdata_standard_nearline
    class: retrieval_nearline
    region: northamerica-northeast2
    data: 10000
```
Also, the region should not matter when it comes to data retrieval from what I understand. 

**Additional context**
The SKUs for these services are:
Archive Data Retrieval	27A1-EBA4-49E8
- https://cloud.google.com/skus/?currency=USD&filter=27A1-EBA4-49E8

Coldline Data Retrieval	1C42-50D6-1B1D
- https://cloud.google.com/skus/?currency=USD&filter=1C42-50D6-1B1D

Nearline Data Retrieval	8D92-97F6-DDF3
- https://cloud.google.com/skus/?currency=USD&filter=8D92-97F6-DDF3

Please let me know if this makes sense or if it is even possible!

**Comment by Cyclenerd** [comment]
Thanks for the input and the great idea. How about this as a format for the usage file.

```yaml
buckets:
  - name: rawdata_nearline
    region: northamerica-northeast2
    class: nearline
    data: 50000
    retrieval: 10000 (retrieval in MB)
```

The modification is related with effort, but it is feasible.
